#!/usr/bin/bash

while true; do
  read -p "Are you sure to initialize? [y/N] "
  case $REPLY in
    "") exit 1;;
    "n" | "N") exit 1;;
    "y" | "Y") break;;
  esac
done

# git
sudo pacman -S git

# paru
sudo pacman -S --needed base-devel
git clone --depth 1 https://aur.archlinux.org/paru.git
cd paru
makepkg -si
cd ..
rm -rf paru

# fish
paru -S fish
chsh -s /usr/bin/fish
echo '
  curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher
  fisher install IlanCosman/tide@v5
  fisher install nickeb96/puffer-fish
  fisher install jorgebucaran/autopair.fish
  fisher install meaningful-ooo/sponge

  set -U fish_greeting
' | fish

# kitty
paru -S kitty
paru -R gnome-terminal
paru -S nautilus-open-any-terminal
dconf write /com/github/stunkymonkey/nautilus-open-any-terminal/terminal kitty
dconf write /com/github/stunkymonkey/nautilus-open-any-terminal/new-tab true

# nvim
paru -S nvim
git clone --depth 1 https://github.com/AstroNvim/AstroNvim.git ~/.config/nvim/

# exa
paru -S exa
echo '
  alias -s ls "exa --icons"
  alias -s ll "exa --icons -l"
  alias -s la "exa --icons -la --git"
  alias -s lt "exa --icons -laT --git --git-ignore git -I .git"
' | fish

# bat
paru -S bat

# downgrade
paru -S downgrade

# debtap
paru -S debtap
sudo debtap -u

# discord
curl -sL https://discord.com/api/download?platform=linux&format=deb -o discord.deb
debtap -q discord.deb
paru -U *.zst --assume-installed gconf
rm *.deb *.zst

# firefox
paru -S firefox

# obsidian
paru -S obsidian-appimage

# rime
paru -S ibus-rime
if [ ! -d ~/.config/ibus/rime/ ]; then
  mkdir -p ~/.config/ibus/rime/
fi
cd ~/.config/ibus/rime/
curl -sL https://raw.githubusercontent.com/rime/plum/master/rime-install | bash
plum/rime-install andy0130tw/iridium-bpmf

# neofetch
paru -S neofetch

# onefetch
paru -S onefetch

# fonts
paru -S ttf-jetbrains-mono
paru -S ttf-nerd-fonts-symbols-2048-em-mono
paru -S noto-fonts-cjk
paru -S noto-fonts-emoji
dconf write /org/gnome/desktop/interface/monospace-font-name 'JetBrains Mono 12'

echo \n\n
neofetch
