#!/usr/bin/bash

while true; do
  read -p "Are you sure to initialize? [y/N] "
  case $REPLY in
    "") exit 1;;
    "n" | "N") exit 1;;
    "y" | "Y") break;;
  esac
done

# git
sudo pacman -S --needed --noconfirm git

# paru
sudo pacman -S --needed --noconfirm base-devel
git clone --depth 1 https://aur.archlinux.org/paru.git
cd paru
makepkg -si
cd ..
rm -rf paru

# homeshick
git clone --depth 1 https://github.com/andsens/homeshick.git ~/.homesick/repos/homeshick/
~/.homesick/repos/homeshick/bin/homeshick clone git@github.com:lumynou5/dotfiles.git

# fish
paru -S --needed --noconfirm fish
chsh -s /usr/bin/fish
echo '
  curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher update

  set -U fish_greeting
' | fish

# kitty
paru -S --needed --noconfirm kitty
paru -R --noconfirm gnome-terminal
paru -S --needed --noconfirm nautilus-open-any-terminal
dconf write /com/github/stunkymonkey/nautilus-open-any-terminal/terminal kitty
dconf write /com/github/stunkymonkey/nautilus-open-any-terminal/new-tab true

# nvim
paru -S --needed --noconfirm nvim
git clone --depth 1 https://github.com/AstroNvim/AstroNvim.git ~/.config/nvim/

# exa
paru -S --needed --noconfirm exa
echo '
  alias -s ls "exa --icons"
  alias -s ll "exa --icons -l"
  alias -s la "exa --icons -la --git"
  alias -s lt "exa --icons -laT --git --git-ignore git -I .git"
' | fish

# bat
paru -S --needed --noconfirm bat

# downgrade
paru -S --needed --noconfirm downgrade

# debtap
paru -S --needed --noconfirm debtap
sudo debtap -u

# discord
curl -sL 'https://discord.com/api/download?platform=linux&format=deb' -o discord.deb
debtap -q discord.deb
paru -U --assume-installed gconf --noconfirm *.zst
rm *.deb *.zst

# firefox
paru -S --needed --noconfirm firefox

# obsidian
paru -S --needed --noconfirm obsidian-appimage

# rime
paru -S --needed --noconfirm ibus-rime
if [ ! -d ~/.config/ibus/rime/ ]; then
  mkdir -p ~/.config/ibus/rime/
fi
cd ~/.config/ibus/rime/
curl -sL https://raw.githubusercontent.com/rime/plum/master/rime-install | bash
plum/rime-install andy0130tw/iridium-bpmf

# neofetch
paru -S --needed --noconfirm neofetch

# onefetch
paru -S --needed --noconfirm onefetch

# fonts
paru -S --needed --noconfirm ttf-jetbrains-mono
paru -S --needed --noconfirm ttf-nerd-fonts-symbols-2048-em-mono
paru -S --needed --noconfirm noto-fonts-cjk
paru -S --needed --noconfirm noto-fonts-emoji
dconf write /org/gnome/desktop/interface/monospace-font-name 'JetBrains Mono 12'

echo -e \n\n
neofetch
